"""blueprint_tiers_row

Revision ID: efc667731c6d
Revises: 5a7e90acfcfc
Create Date: 2026-07-26 21:49:32.726453

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'efc667731c6d'
down_revision = '5a7e90acfcfc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blueprints', sa.Column('tiers', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blueprints', 'tiers')
    # ### end Alembic commands ###
